[versions]
kotlin="1.8.21"

logback="1.4.6"
minio="8.5.8"

log4j="1.4.0"

exposedVersion="0.46.0"
coroutinesVersion="1.6.1-native-mt"
serializationVersion="1.3.2"
datetimeVersion="0.4.0"
ktorVersion="2.3.8"

logbackEncoderVersion="7.3"
prometheusVersion="1.11.2"
uuidVersion="0.5.0"
kotlinCorVersion="0.5.5+"

[libraries]
minio = { module = "io.minio:minio", version.ref = "minio"}
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback"}
log4j-api-kotlin = { module = "org.apache.logging.log4j:log4j-api-kotlin", version.ref = "log4j"}


[plugins]
#kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
